### ISSUE TITLE
Issue with updating cert

### ISSUE THREAD

**Issue by olha-yukhno** [nginx-le/nginx-le#29] opened 2019-08-14 15:08 UTC
Hi, we got a problem with automatic updating:
`trying to update letsencrypt ...
letsencrypt certificate /etc/nginx/ssl/le-crt.pem still valid
'/etc/nginx/conf.d.disabled' -> '/etc/nginx/conf.d/conf.d.disabled'
mv: can't rename '/etc/nginx/conf.d.disabled': No such file or directory
reload nginx with ssl`

Looks like problem is in [entrypoint.sh in row 52](https://github.com/umputun/nginx-le/blob/master/script/entrypoint.sh#L52). Folder was moved during first cycle pass.
As folder was created before the cycle, on second cycle pass (after 10d) we got an error while trying to move it again.

Can you check this issue pls :)

**Comment by umputun** [comment] 2019-08-14 17:53
I think the issue is displaying/reporting only. "disable ssl configuration" step needed only to run nginx for the first time before initial certificates generated.

If this the issue you see (i.e. everything is working, certs updating but error message appearing on refresh) it can be fixed by adding a check for cert presence or just by suppressing the error with `2> /dev/null`

**Comment by paskal** [comment] 2019-08-14 18:25
@olha-yukhno, thank you for the report! I've managed to replicate this by killing "sleep 10d" in the container:
```
nginx             | start letsencrypt updater
nginx             | trying to update letsencrypt ...
nginx             | letsencrypt certificate /etc/nginx/ssl/le-crt.pem still valid
nginx             | '/etc/nginx/conf.d.disabled' -> '/etc/nginx/conf.d'
nginx             | reload nginx with ssl
nginx             | 2019/08/14 18:21:16 [notice] 34#34: signal process started
nginx             | Terminated
nginx             | trying to update letsencrypt ...
nginx             | letsencrypt certificate /etc/nginx/ssl/le-crt.pem still valid
nginx             | mv: can't rename '/etc/nginx/conf.d.disabled': No such file or directory
nginx             | '/etc/nginx/conf.d.disabled' -> '/etc/nginx/conf.d/conf.d.disabled'
nginx             | reload nginx with ssl
nginx             | 2019/08/14 18:21:57 [notice] 62#62: signal process started
nginx             | Terminated
nginx             | trying to update letsencrypt ...
nginx             | letsencrypt certificate /etc/nginx/ssl/le-crt.pem still valid
nginx             | mv: can't rename '/etc/nginx/conf.d.disabled': No such file or directory
nginx             | '/etc/nginx/conf.d.disabled' -> '/etc/nginx/conf.d/conf.d.disabled'
nginx             | reload nginx with ssl
nginx             | 2019/08/14 18:22:07 [notice] 80#80: signal process started
```
[Command above](https://github.com/umputun/nginx-le/blob/master/script/entrypoint.sh#L51) silently removes file and don't write anything in case there is no file to remove. To make behavior consistent I'll prepare PR which silences this message as well.

**Closed as completed** 2019-08-14 19:00 UTC
